name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    # action Cypress
    - name: Cypress run
      uses: cypress-io/github-action@v2.8.2
      with:
        record: true
        group: 'teste'
      env: 
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    
    # action video upload
    - name: Upload videos
      uses: actions/upload-artifact@v2.2.0
      if: always()
      with:
        name: videos
        path: cypress/videos
